export default [
  {
    pid: -1,
    id: 31,
    children: [
      {
        pid: 31,
        id: 39,
        children: [],
        label: '综合布线勘察',
        pos: [0, 0],
      },
      {
        pid: 31,
        id: 40,
        children: [
          {
            pid: 40,
            id: 85,
            children: [],
            label: '监控点位',
            pos: [0, 1, 0],
          },
          {
            pid: 40,
            id: 86,
            children: [],
            label: 'AP点位',
            pos: [0, 1, 1],
          },
          {
            pid: 40,
            id: 87,
            children: [],
            label: '收银点位',
            pos: [0, 1, 2],
          },
          {
            pid: 40,
            id: 88,
            children: [],
            label: '音响点位',
            pos: [0, 1, 3],
          },
        ],
        label: '设备安装点位勘察',
        pos: [0, 1],
      },
    ],
    label: '现场勘察',
    pos: [0],
  },
  {
    pid: -1,
    id: 32,
    children: [],
    label: '综合布线',
    pos: [1],
  },
  {
    pid: -1,
    id: 33,
    children: [
      {
        pid: 33,
        id: 95,
        children: [],
        label: '端接安装',
        pos: [2, 0],
      },
      {
        pid: 33,
        id: 54,
        children: [],
        label: '定位一体机',
        pos: [2, 1],
      },
      {
        pid: 33,
        id: 53,
        children: [],
        label: '门禁',
        pos: [2, 2],
      },
      {
        pid: 33,
        id: 52,
        children: [],
        label: '电子价签',
        pos: [2, 3],
      },
      {
        pid: 33,
        id: 51,
        children: [],
        label: '考勤机',
        pos: [2, 4],
      },
      {
        pid: 33,
        id: 50,
        children: [],
        label: '红外报警器',
        pos: [2, 5],
      },
      {
        pid: 33,
        id: 43,
        children: [],
        label: '无线AP',
        pos: [2, 6],
      },
      {
        pid: 33,
        id: 49,
        children: [],
        label: '叫号机',
        pos: [2, 7],
      },
      {
        pid: 33,
        id: 41,
        children: [],
        label: '监控设备',
        pos: [2, 8],
      },
      {
        pid: 33,
        id: 48,
        children: [],
        label: '电视',
        pos: [2, 9],
      },
      {
        pid: 33,
        id: 47,
        children: [],
        label: '小票打印机',
        pos: [2, 10],
      },
      {
        pid: 33,
        id: 44,
        children: [],
        label: '背景音乐',
        pos: [2, 11],
      },
      {
        pid: 33,
        id: 45,
        children: [],
        label: 'KDS',
        pos: [2, 12],
      },
      {
        pid: 33,
        id: 46,
        children: [],
        label: '收银机',
        pos: [2, 13],
      },
    ],
    label: '设备安装',
    pos: [2],
  },
  {
    pid: -1,
    id: 34,
    children: [
      {
        pid: 34,
        id: 56,
        children: [],
        label: '机柜线路整理',
        pos: [3, 0],
      },
      {
        pid: 34,
        id: 57,
        children: [],
        label: '机柜设备上架',
        pos: [3, 1],
      },
      {
        pid: 34,
        id: 58,
        children: [],
        label: '机柜线路端接',
        pos: [3, 2],
      },
      {
        pid: 34,
        id: 59,
        children: [],
        label: '机柜线路测试',
        pos: [3, 3],
      },
      {
        pid: 34,
        id: 60,
        children: [],
        label: '机柜标签标识',
        pos: [3, 4],
      },
    ],
    label: '机柜安装',
    pos: [3],
  },
  {
    pid: -1,
    id: 35,
    children: [
      {
        pid: 35,
        id: 62,
        children: [],
        label: '监控系统',
        pos: [4, 0],
      },
      {
        pid: 35,
        id: 61,
        children: [],
        label: '网络系统',
        pos: [4, 1],
      },
      {
        pid: 35,
        id: 63,
        children: [],
        label: '无线系统',
        pos: [4, 2],
      },
      {
        pid: 35,
        id: 64,
        children: [],
        label: '收银机系统',
        pos: [4, 3],
      },
      {
        pid: 35,
        id: 65,
        children: [],
        label: '门禁系统',
        pos: [4, 4],
      },
      {
        pid: 35,
        id: 66,
        children: [],
        label: '电子价签系统',
        pos: [4, 5],
      },
      {
        pid: 35,
        id: 67,
        children: [],
        label: '客流统计系统',
        pos: [4, 6],
      },
      {
        pid: 35,
        id: 68,
        children: [],
        label: '拼接屏系统',
        pos: [4, 7],
      },
      {
        pid: 35,
        id: 69,
        children: [],
        label: '定位一体机系统',
        pos: [4, 8],
      },
    ],
    label: '设备调试',
    pos: [4],
  },
  {
    pid: -1,
    id: 36,
    children: [
      {
        pid: 36,
        id: 70,
        children: [],
        label: '内部验收',
        pos: [5, 0],
      },
      {
        pid: 36,
        id: 71,
        children: [],
        label: '客户验收',
        pos: [5, 1],
      },
    ],
    label: '项目验收',
    pos: [5],
  },
  {
    pid: -1,
    id: 37,
    children: [],
    label: '开业值守',
    pos: [6],
  },
  {
    pid: -1,
    id: 38,
    children: [
      {
        pid: 38,
        id: 72,
        children: [],
        label: '门店安装设备清单',
        pos: [7, 0],
      },
    ],
    label: '完工报告',
    pos: [7],
  },
];
